### ISSUE TITLE
Reviews tests fail due to missing 'Write a review' button

### ISSUE THREAD

**Issue by davehunt** [mozilla/marketplace-tests#710] opened 2015-08-18 13:40 UTC
All the tests that create a review failed today because the 'Write a review' button was not present on https://marketplace-dev.allizom.org/app/delicious-stew-11/?src=search after signing in.

In each case the user was a temporary generated Firefox Account user. @krupa do you have any ideas why this button would not be present? See the screenshot below:

![screenshot](https://cloud.githubusercontent.com/assets/122800/9331345/d2db5410-45b6-11e5-850f-8d343f73b2e6.png)

**Comment by krupa** [comment] 2015-08-18 16:49
@davehunt that test shouldn't be failing. I tried reproducing the issue with a new user and the flow worked fine for me. The button is not present in two scenarios - a) It is a paid app you have not yet purchased b) the app is not available in your region. Both cases don't apply to the app under test.

I will investigate further and report back.

**Comment by stephendonner** [comment] 2016-05-05 21:06
Closing due to https://github.com/mozilla/marketplace-tests/issues/760

**Closed by stephendonner** 2016-05-05 21:06 UTC
Labels: priority medium, Test Failure
