### ISSUE TITLE
Retire all tests related to payments on Marketplace

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#751] opened 2016-02-10 22:11 UTC
We have a few payments tested which have been xfailed for a while. Let us retire them. Thanks!

**Comment by davehunt** [comment] 2016-02-11 09:23
It looks like #748 is a duplicate of this. As this covers multiple tests though, let's keep this one open.

**Comment by davehunt** [comment] 2016-02-11 09:26
@krupa I can only find [one test](https://github.com/mozilla/marketplace-tests/blob/4cc0037d6ddafc8d2e8c36e04f76d782d7f0f44f/tests/desktop/consumer_pages/test_purchase_app.py) are you aware of any others?

**Comment by davehunt** [comment] 2016-03-10 11:41
Pull request #755 submitted for review.

**Comment by davehunt** [comment] 2016-03-11 08:42
Fixed in https://github.com/mozilla/marketplace-tests/pull/755

**Closed by davehunt** 2016-03-11 08:42 UTC
Labels: difficulty beginner, priority medium
