### ISSUE TITLE
Update tests to not use Test Zippy With Me

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#679] opened 2015-05-28 17:48 UTC
We used to use the test app Test Zippy With Me to test the reference implementation for payment. Since we switched to fake apps, all paid apps on dev use zippy. Instead of depending on Test Zippy With Me, let's just use and :paid app.

https://webqa-ci.mozilla.com/view/Buildmaster/job/marketplace.mozilla-b2g32_v2_0.nightly/236/HTML_Report/

**Comment by bobsilverberg** [comment] 2015-05-28 20:43
@krupa I am actively working on this. The job you reference is for the FxOS tests, so the issue belongs to that repo. Do you mind closing this and opening it for that repo?

**Comment by bobsilverberg** [comment] 2015-05-29 11:45
Closing as a duplicate of https://github.com/mozilla/marketplace-tests-gaia/issues/114

**Closed by bobsilverberg** 2015-05-29 11:45 UTC
